name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - uses: retypeapp/action-build@latest
        with:
            config: retype-en.yml
            base: docs/en/

      - uses: retypeapp/action-build@latest
        with:
            config: retype-ko.yml
            base: docs/ko/

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
